### ISSUE TITLE
Threaded block signing

### ISSUE THREAD

**Issue by heifner** [eosnetworkfoundation/mandel#158]
- https://github.com/EOSIO/eos/pull/10876

This allows for support of slower block signing mechanisms without blocking the main thread while signing the block. It does however, complicate the code and breaks assumptions of plugins on order of signals: `block_start`, `block_abort`, `accepted_block`.
The next block is started before the previous block is sent out.

**Comment by spoonincode** [comment]
I'm doubtful the complexity is justified given lack of HSM uptake by BPs.

**Comment by matthewdarwin** [comment]
What is HSM?

**Comment by spoonincode** [comment]
Hardware security module. They usually sign rather slowly (think 30ms+), so holding up the main thread for 30ms while waiting on the HSM to squeeze out a signature is rather disruptive. Without HSM usage the improvement here is rather minor for more than minor complexity added. imo not a good tradeoff.

**Comment by heifner** [comment]
I tend to agree that the trade off is not worth it. However, if we determined we wanted to use that time for something else like say waiting on confirmations of validation from other nodes or off host signing or ??? then this could be revisited. It is working nicely in eosio.

**Comment by spoonincode** [comment]
The time for a signature on average is negligible: a K1 signature on my box is 22µs. Now, due to EOSIO/eos#6699, the average signature time is actually longer and there can be some very pessimistic times if you're unlucky. e.g. from that data, a few times out of every 74000 blocks you're going to spend 22µs*17 = 374µs which is starting to get a little concerning.

If we implement the new fast finality protocol with Schnorr signatures we have the opportunity to fix that dumb defect and always sign once.

But I seem to recall there were some improvements measured here beyond just signing. I'd have to look at the PR more to remind myself what.

**Comment by heifner** [comment]
If this is ever back-ported, there is a bug in that `process_unapplied_trx` calls `complete_produced_block_if_ready()` which can invalidate the iterator.

**Comment by spoonincode** [comment]
Closing this out as wont-do for now. The benefit doesn't outweigh the increased complexity
