### ISSUE TITLE
port over resource monitor plugin

### ISSUE THREAD

**Issue by spoonincode** [eosnetworkfoundation/mandel#172]
Resource monitor plugin was a feature added in 2.1+ to optionally shutdown nodeos when disk usage reached a certain threshold. It is difficult for nodeos to cleanly shut it self down when a disk write fails due to all the asynchrony, so proactively shutting down early can be a safe option.

Read more in EOSIO/eos#9098

**Comment by eosusa** [comment]
totally understand, but maybe i can give a bit of context to why its so painful as a node operator:

* when the drive hosting the ship logs fills up, the node continues syncing the blocklog forward and just stops updating ship and gets further and further our of sync, making it more and more difficult to repair and resync (once you find it because ship just stops serving current blocks).  the good news is the ship logs are normally better about being able to repair themselves after corruption (although can take hours on active chains).  get_info and api calls continue to work, so difficult to detect until dependent services detect the lag in ship data.

* when the drive containing the blocklog fills up, its really a crapshoot as to where the log seems to have stopped writing.  many times, the log is corrupted to the point a snapshot restore cant complete because the replay constantly fails.  in those cases, sometimes i can use eosio-blocklog to trim a few 1000 blocks and can get things back in line, but many of those cases even eosio-blocklog is unable to repair the blocklog, and since the replay wont work either, I'm left with no other choice other than blast it all and resync/copy in files (which could be TBs and TBs).

It took me many years of fighting eosio crashes to figure out all the symptomatic error messages and what the potential resolution steps might be and have successfully destroyed dozens and dozens of nodes over the years like this.  Seems even like a periodic check of free space with a threshold and safe shutdown might be a simple solution, but I'm also not the man to write that code to make it happen :)

**Comment by spoonincode** [comment]
Multiple positive feedback, moving this up to 3.1 potential

**Comment by oschwaldp-oci** [comment]
Based on @spoonincode's recommendation I will target this effort to back port resource monitor changes based on those that were merged into develop. Here is what I am thinking:

Backport:
https://github.com/EOSIO/eos/pull/9196
https://github.com/EOSIO/eos/pull/9826
https://github.com/EOSIO/eos/pull/10308
https://github.com/EOSIO/eos/pull/10601
