### ISSUE TITLE
Remove unnecessary strlen

### ISSUE THREAD

**Issue by heifner** [eosnetworkfoundation/mandel#241]
Backport https://github.com/EOSIO/eos/pull/9368

**Comment by spoonincode** [comment]
afaik not applicable. This was a performance improvement for the new host function wrappers which had/has performance problems. The new host function wrappers were never brought over to Mandel because they were only needed for KV so far.

**Comment by heifner** [comment]
That code is in Mandel

**Comment by spoonincode** [comment]
hm you're right. what happened here...

**Comment by spoonincode** [comment]
I guess #197 should have been the hint to me that we _did_ bring those over. I'm probably thinking either early in mandel's fork how they weren't there, or possibly since there was no need to make the change that it wouldn't have been done.

What a disappointment. That change is responsible for a huge performance regression that was never fixed.

**Comment by heifner** [comment]
It came over with: https://github.com/eosnetworkfoundation/mandel/pull/2
