### ISSUE TITLE
Backport: Add trace plugin API test

### ISSUE THREAD

**Issue by linh2931** [eosnetworkfoundation/mandel#427]
https://github.com/EOSIO/eos/pull/9194

trace_plugin_test.py was pulled into Mandel by the removing history plugin activity. But it was not enabled in CMakefile. Need to test and enable it.

**Comment by oschwaldp-oci** [comment]
Looks like https://github.com/eosnetworkfoundation/mandel/issues/399 didn't end up being backported due to the bug not manifesting in `mandel`.  However, I think it would be wise to still backport the test and util updates, so I will endeavor to do that in this issue as well.  Will not backport updates to `cleos` (though might need to at a future date if updating the json format).

Backports `tests/*` changes from https://github.com/EOSIO/eos/pull/8931

**Comment by oschwaldp-oci** [comment]
After further research, it looks like we need to backport: https://github.com/EOSIO/eos/pull/8676 to get the data unpacking.  Then the bug does resurface necessitating all of https://github.com/EOSIO/eos/pull/8931.

So, will work this as 3 backports:
[] backport: https://github.com/EOSIO/eos/pull/8676
[] backport: https://github.com/EOSIO/eos/pull/8931 (https://github.com/eosnetworkfoundation/mandel/issues/399)
[] backport: https://github.com/EOSIO/eos/pull/9194
