### ISSUE TITLE
Backport: Use NET bill in transaction receipt during light validation mode

### ISSUE THREAD

**Issue by ClaytonCalabrese** [eosnetworkfoundation/mandel#559]
> Since the NET bill is objective, a node in full validation mode is able to calculate what the NET bill for a transaction should be. Even with this change, a node in full validation mode will always compute the NET bill rather than blindly trusting the NET bill provided by the producer in the transaction receipt and it will reject the block if there is a mismatch.

However, with the changes in this PR, a node operating in a mode where the normal transaction checks are skipped (light validation mode or applying a block by a trusted producer) will now simply use the NET bill provided by the producer in the transaction receipt rather than computing the amount itself. This sets the stage for later changes that allow a light validation node to apply a block that may have had some context-free data within the block removed, which would make it impossible to calculate the correct NET bill.

This PR also adds a new unit test, resource_limits_test/light_net_validation, to test the new behavior.

Backports: https://github.com/EOSIO/eos/pull/8856

**Comment by heifner** [comment]
This was part of prunable CFD which is not needed in Mandel.

**Comment by arhag** [comment]
@heifner: I changed the close status of this issue to "Closed as not planned" since we decided to not complete the task represented by this issue but instead discard it since we do not want to fix it. It turns out I don't even need to re-open it to close it again. The drop down allows me to change the close status of an already closed issue.
