### ISSUE TITLE
/v1/producer/get_supported_protocol_features returns wrong information after upgrade from rc1 to rc2

### ISSUE THREAD

**Issue by matthewdarwin** [eosnetworkfoundation/mandel#687]
Going from mandel-3.1.0-rc1 to mandel-3.1.0-rc2, the description_digest of several protocol features changed.
When running rc1, there are files created in configdir/protocol_features.
When upgrading to rc2, these files are not re-generated.
When running http://localhost:8888/v1/producer/get_supported_protocol_features on rc2 it returns the information from rc1.

Workaround, remove the files when upgrading from rc1 to rc2.

nodeos must fail with error of inconsistent information instead of using the wrong information.

**Comment by arhag** [comment]
The software technically allows the operator of the node to change the metadata of a protocol feature which results in computing a different (and thus network incompatible) `feature_digest` for the protocol feature. This is particular meant for future data-driven protocol features more so than built-in ones.

So I don't think it would be correct behavior to disallow starting nodeos with built-in protocol features with different metadata (and thus different `feature_digest`s) than the default ones hard-coded in the nodeos binary

That said, there is very little value in changing the non-subjective metadata (the ones that actually impact the `feature_digest`) of a `builtin` protocol feature from its default. So I can see value in providing an optional mode of starting up nodeos in which nodeos scans through all the protocol features in the `protocol_features` directory (as it currently does), but then compares the `feature_digest`s of `builtin` protocol features to the corresponding ones expected in a default configuration in order to check for any differences, and possibly terminates nodeos startup if there is a mismatch.

To avoid breaking compatibility, we could have an config option to determine this mode and make it default to only warning about mismatches in `built` protocol feature digests on startup. Other options would include not warning about (good for nodes intentionally setup for a network that avoids the stock protocol feature metadata) as well as one to treat mismatches as an error (and abort nodeos startup). Most people would likely choose to run with the stock protocol feature metadata and would therefore see value in running in this error mode.

If we wish to move the default to the error mode in the future, we can print a warning about how this will be a fatal startup error in the future and wait to switch the default mode to error in a future major version release.

**Comment by arhag** [comment]
Alternatively, since this could be a significant enough pain point for everyone upgrading from 3.1.0-rc1, we can just make immediately make the default mode of the new option to abort on mismatch despite it being a breaking change (with a helpful message on how to change that option if the user actually intended to go against the stock protocol feature configuration). Technically 3.1.0 is the release where we are allowed to introduce breaking changes (compared to upgrades from 2.0.x). So might as well take advantage of it to reduce confusion.

**Comment by stephenpdeos** [comment]
This will not be handled as a release blocker primarily due to infrequency of use of this feature along with the number of people who are moving through RCs. Even those who are following along are connected to the team and will be informed of this issue to avoid most of the pain.

In the future, we will always communicate hash changes clearly in release notes to help hedge against this.
